/**
 * This is a Next.js home page component that imports necessary modules and components, sets metadata
 * for the page, and renders a layout with a hero section.
 * @returns The `Home` component is being returned as the default export.
 */
// Importing necessary modules and styles
import Head from "next/head";
import Image from "next/image";
import Layout from "@/components/Layout";
import Hero from "@/components/Hero";
import { useUser } from "@/lib/authContext";
import Places from "./organizer/map";
import MainEvents from "@/components/MainEvents";
import { fetcher } from "@/lib/api";

// Defining the component that will be exported as default
export default function Home() {
  const { user, loading } = useUser();
  return (
    <>
      {/* Setting the head and metadata for the page */}
      <Head>
        <title>Soukticket || Billeterie 🎟</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout user={user}>
        {/* The main content of the page */}
        <Hero />
        <MainEvents />
      </Layout>
    </>
  );
}
